### ISSUE TITLE
[Feature Request]A FastTESR example would be nice

### ISSUE THREAD

**Issue by V0idWa1k3r** [Cadiboo/Example-Mod#3]
In modern forge there is an option to render TileEntities in batch with only one draw call greatly reducing the performance impact on the game. However most modders are either not aware of this ability or don't know how to use it which is a real shame since it really helps with the performance of the game. I would like to propose an inclusion of a FastTESR example in this example mod to help beginners understand how it works, maybe with some helper methods. I could make one and submit a PR if you want. Feel free to close this issue if you don't think your example mod needs an example of a FastTESR :)

**Comment by Cadiboo** [comment]
This mod is meant to be a base setup to easily start Modding (so it focuses on conventions & code practices more than actual examples - I’m planning on linking some good reference projects in the README) and I didn’t originally add a Tile Entoty because not all mods include Tile Entities. However they are pretty common, and I’ve been planning on adding one for a while. I was planning on adding 2 furnace Tile Entities written with capabilities, one using blockstates and the other using a TESR. So a FastTESR PR would be appreciated
